Series: Modified to work for exercism checker

diff --git a/homework/Bash11.7.26/series b/homework/Bash11.7.26/series
--- a/homework/Bash11.7.26/series
+++ b/homework/Bash11.7.26/series
@@ -1,17 +1,27 @@
-#!/bin/bash
 
+#!/bin/bash
 # ciel je aby uzivatel zadal cislo a dlzku subskupiny a vytvorit skupiny 14345 a 2
 # => 1434 & 4345
-
-read -p "Number: " num
-read -p "# of digits in series: " n
-
+#read -p "Number: " num
+#read -p "# of digits in series: " n
+num="$1"
+n="$2"
+output=()
 fin=0
-if (( ${#num} < ${n} )); then   
-    echo "No bueno"
+if (( ${#num} == 0 )); then
+    echo "series cannot be empty"
+    exit 1
+elif (( n < 1 )); then
+    echo "slice length cannot be negative"
+    echo "slice length cannot be zero"
+    exit 1
+elif (( n > ${#num} )); then
+    echo "slice length cannot be greater than series length"
+    exit 1
 else
     for (( i=0 ; i< (${#num} - n) + 1 ; i++ )); do
         fin=${num:i:n}
-        echo "${fin}"
+        output+=("${fin}")
     done
+    echo "${output[@]}"
 fi
