POSTINST_NOTES: Recovery and fixing of notes

diff --git a/homework/filesytemsandvariables/postinst_notes b/homework/filesytemsandvariables/postinst_notes
--- a/homework/filesytemsandvariables/postinst_notes
+++ b/homework/filesytemsandvariables/postinst_notes
@@ -3,51 +3,42 @@
 # Copyright 2009 The Chromium Authors
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
-
-set -e
-
+set -e #Exit if command has nonzero exit
 # System-wide package configuration.
-DEFAULTS_FILE="/etc/default/google-chrome"
-
+DEFAULTS_FILE="/etc/default/google-chrome" #Sets shell (not env no export function) variable to string
 # Add icons to the system icons
-XDG_ICON_RESOURCE="`command -v xdg-icon-resource 2> /dev/null || true`"
-if [ ! -x "$XDG_ICON_RESOURCE" ]; then
-  echo "Error: Could not find xdg-icon-resource" >&2
-  exit 1
-fi
-for icon in  product_logo_16.png product_logo_24.png product_logo_32.png product_logo_48.png product_logo_64.png product_logo_128.png product_logo_256.png; do
-  size="$(echo ${icon} | sed 's/[^0-9]//g')"
-  "$XDG_ICON_RESOURCE" install --size "${size}" "/opt/google/chrome/${icon}" \
+XDG_ICON_RESOURCE="`command -v xdg-icon-resource 2> /dev/null || true`" #Sets variable to subshell output of cheching where the xdg command is, while throwing away the error or sets the value to true
+if [ ! -x "$XDG_ICON_RESOURCE" ]; then # tests and negates wether the file is executable
+    echo "Error: Could not find xdg-icon-resource" >&2 # prints error message and gives error to STDERR
+  exit 1 # exits the program with code 1
+fi # closes if statement
+for icon in  product_logo_16.png product_logo_24.png product_logo_32.png product_logo_48.png product_logo_64.png product_logo_128.png product_logo_256.png; do # for each png in icon do the following
+  size="$(echo ${icon} | sed 's/[^0-9]//g')" # variable size is the subshell output of the name piped into a regex thing that changes the name to only numbers
+  "$XDG_ICON_RESOURCE" install --size "${size}" "/opt/google/chrome/${icon}" \ # Runs the tool and installs the specified size from the opt file
     "google-chrome"
 done
-
 # Update cache of .desktop file MIME types. Non-fatal since it's just a cache.
-update-desktop-database > /dev/null 2>&1 || true
-
-# Updates defaults.list file if present.
-update_defaults_list() {
+update-desktop-database > /dev/null 2>&1 || true # sets STDERR to discard# Updates defaults.list file if present.
+update_defaults_list() { #sets a functions
   # $1: name of the .desktop file
-
-  local DEFAULTS_LIST="/usr/share/applications/defaults.list"
-
-  if [ ! -f "${DEFAULTS_LIST}" ]; then
-    return
+  local DEFAULTS_LIST="/usr/share/applications/defaults.list" #local shell variable
+  if [ ! -f "${DEFAULTS_LIST}" ]; then # tests if there isnt a file called that?
+      return
   fi
-
   # Split key-value pair out of MimeType= line from the .desktop file,
   # then split semicolon-separated list of mime types (they should not contain
   # spaces).
-  mime_types="$(grep MimeType= /usr/share/applications/${1} |
+  mime_types="$(grep MimeType= /usr/share/applications/${1} | 
                 cut -d '=' -f 2- |
-                tr ';' ' ')"
-  for mime_type in ${mime_types}; do
-    if egrep -q "^${mime_type}=" "${DEFAULTS_LIST}"; then
+                tr ';' ' ')" # Sets a var to the subshell resulst of finds something with pos pam 1 then give the result to cut which separates the field before the = sign and specifies to display the first 2 words of each line and then gives the result to translate all semicolons to spaces   
+  for mime_type in ${mime_types}; do # for a counter for each element is mime_types do the following
+    if egrep -q "^${mime_type}=" "${DEFAULTS_LIST}"; then #If something is extended greped and is equal to default list then do the following
       if ! egrep -q "^${mime_type}=.*${1}" "${DEFAULTS_LIST}"; then
-        default_apps="$(grep ${mime_type}= "${DEFAULTS_LIST}" |
+        default_apps="$(grep ${mime_type}= "${DEFAULTS_LIST}" | #Set var from a subshell wether the searched variable is equal to the other variable and then pipe the result to cut to keep everything before the = and keep the first two words of each line 
                         cut -d '=' -f 2-)"
-        egrep -v "^${mime_type}=" "${DEFAULTS_LIST}" > "${DEFAULTS_LIST}.new"
-        echo "${mime_type}=${default_apps};${1}" >> "${DEFAULTS_LIST}.new"
-        mv "${DEFAULTS_LIST}.new" "${DEFAULTS_LIST}"
+        egrep -v "^${mime_type}=" "${DEFAULTS_LIST}" > "${DEFAULTS_LIST}.new" # Print the stuff that doesent start with mime_type and put the reuslt into defaults list new
+        echo "${mime_type}=${default_apps};${1}" >> "${DEFAULTS_LIST}.new" # Append the new things?
+        mv "${DEFAULTS_LIST}.new" "${DEFAULTS_LIST}" #Copies the file without a suffix
       fi
     else
       # If there's no mention of the mime type in the file, add it.
@@ -55,8 +46,7 @@ update_defaults_list() {
     fi
   done
 }
-
-update_defaults_list "google-chrome.desktop"
+update_defaults_list "google-chrome.desktop" #Calls the function
 
 # This function uses sed to insert the contents of one file into another file,
 # after the first line matching a given regular expression. If there is no
